### ISSUE TITLE
When i using SelectStatementProvider api

### ISSUE THREAD

**Issue by MaLuxray** [mybatis/mybatis-dynamic-sql#732]
mybatis dynamic SQL version >= 1.4.0

in my java code

``` java
    SelectStatementProvider selectStatement = select(count())
                .from(PatientRecipeServiceDynamicSqlSupport.patientRecipeService)
                .leftJoin(HisPatientProfileDynamicSqlSupport.hisPatientProfile)
                .on(PatientRecipeServiceDynamicSqlSupport.patientId, equalTo(HisPatientProfileDynamicSqlSupport.id))
                .where(PatientRecipeServiceDynamicSqlSupport.id, isEqualToWhenPresent((Long) null))
                .build().render(RenderingStrategies.MYBATIS3);

   System.out.println(selectStatement.getSelectStatement());
```

exception message

```
   Exception in thread "main" org.mybatis.dynamic.sql.exception.NonRenderingWhereClauseException: A where clause was specified, but failed to render
	at org.mybatis.dynamic.sql.where.render.WhereRenderer.render(WhereRenderer.java:37)
	at org.mybatis.dynamic.sql.select.render.QueryExpressionRenderer.renderWhereClause(QueryExpressionRenderer.java:188)
	at java.util.Optional.flatMap(Optional.java:241)
	at org.mybatis.dynamic.sql.select.render.QueryExpressionRenderer.calculateWhereClause(QueryExpressionRenderer.java:179)
	at org.mybatis.dynamic.sql.select.render.QueryExpressionRenderer.render(QueryExpressionRenderer.java:124)
	at org.mybatis.dynamic.sql.select.render.SelectRenderer.renderQueryExpression(SelectRenderer.java:74)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.mybatis.dynamic.sql.select.render.SelectRenderer.render(SelectRenderer.java:53)
	at org.mybatis.dynamic.sql.select.SelectModel.render(SelectModel.java:65)
	at com.ipharmacare.opm.service.impl.PatientRecipeServiceSelectServiceImpl.main(PatientRecipeServiceSelectServiceImpl.java:86)
```

**Comment by jeffgbutler** [comment]
This is working as designed. See this doc page for details about how to allow this statement to render: https://mybatis.org/mybatis-dynamic-sql/docs/configuration.html

**Comment by MaLuxray** [comment]
@jeffgbutler Thank you for your answer
